language: python
python: 3.4
sudo: false
env:
  - TOX_ENV=docs
  - TOX_ENV=lint
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py27-djangomaster
  - TOX_ENV=py33-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django110
  - TOX_ENV=py34-djangomaster
install:
- pip install tox
script:
- tox -e $TOX_ENV
cache:
  directories:
    - $HOME/.cache/pip
